version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
# ApplicationStop:
# DownloadBundle:

# Install:
  BeforeInstall:
    - location: server/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: server/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server/scripts/application_start.sh
      timeout: 300
      runas: root
# ValidateService:
